#!/bin/bash
# filter/30800.sh
# Handles NOSTR kind:30800 (parameterized replaceable events) in UPlanet.
#
# Known d-tag values:
#   cooperative-config  → published exclusively by uplanet.G1.nostr (G1HEX)
#   did                 → player DID documents (any authorized NOSTR card)
#
# Security: prevents any authorized player from impersonating the cooperative
# configuration publisher (fake cooperative-config events).

MY_PATH="`dirname \"$0\"`"
MY_PATH="`( cd \"$MY_PATH\" && pwd )`"

source "$MY_PATH/common.sh"

LOG_FILE="$HOME/.zen/tmp/nostr_30800.log"
ensure_log_dir "$LOG_FILE"

log_30800() {
    log_with_timestamp "$LOG_FILE" "$1"
}

event_json="$1"
extract_event_data "$event_json"
extract_tags "$event_json" "d"
d_tag="$d"

log_30800 "KIND 30800: pubkey=${pubkey:0:8}... d=${d_tag:-'<none>'}"

case "$d_tag" in
    "cooperative-config")
        # Only the station's own uplanet.G1.nostr key may publish cooperative-config.
        # G1HEX is the secp256k1 hex of keygen(UPLANETNAME.G1, UPLANETNAME.G1),
        # generated by UPLANET.refresh.sh and served at /UPLANET/G1HEX.
        G1HEX_FILE="$HOME/.zen/tmp/${IPFSNODEID}/UPLANET/G1HEX"
        if [[ ! -s "$G1HEX_FILE" ]]; then
            # Relay not fully initialized yet — accept with warning
            log_30800 "WARN: G1HEX not found (${G1HEX_FILE}) — accepting (relay not initialized)"
            echo ">>> (30800) WARN: cooperative-config accepted without G1HEX check (relay init pending)"
            exit 0
        fi

        EXPECTED_G1HEX=$(tr -d '[:space:]' < "$G1HEX_FILE")

        if [[ "$pubkey" == "$EXPECTED_G1HEX" ]]; then
            log_30800 "ACCEPTED: cooperative-config from station G1 key ${pubkey:0:8}..."
            echo ">>> (30800) cooperative-config from ${pubkey:0:8}..."
            exit 0
        else
            log_30800 "REJECTED: cooperative-config from unauthorized key ${pubkey:0:8}... (expected: ${EXPECTED_G1HEX:0:8}...)"
            echo ">>> (30800) REJECTED: fake cooperative-config from ${pubkey:0:8}..."
            exit 1
        fi
        ;;

    "did")
        # Player DID documents — authorized NOSTR cards only (already checked by process.sh)
        log_30800 "ACCEPTED: DID document from ${pubkey:0:8}..."
        echo ">>> (30800) DID from ${pubkey:0:8}..."
        exit 0
        ;;

    *)
        # Forward compatibility: accept other d-tag values from authorized keys
        log_30800 "ACCEPTED: kind 30800 d='${d_tag:-<none>}' from ${pubkey:0:8}... (forward compat)"
        echo ">>> (30800) kind 30800 d='${d_tag}' from ${pubkey:0:8}..."
        exit 0
        ;;
esac
